# This file is used by the jenkins job

# Dependencies with explicit versions are provided by the copr repository.

# (migi) flake8 is added to tox.ini for removing ugly warning:
#        WARNING:test command found but not installed in testenv
#
# (migi) to keep track of exact packages from outside of rhelosp repo
#        all deps from copr are listed, even if those were dependency
#        requirements from other packages being installed
pep8:

    rpm_deps: [
      python-hacking-0.9.2
    ]

    remove_rpm: []

    run:
        sed -i '/flake8 {posargs}/a whitelist_externals = flake8' tox.ini;
        tox --sitepackages -v -e pep8 2>&1 | tee ../logs/testrun.log;


# (migi) python-ceilometer is installed and then removed to satisfy all runtime
#        dependencies for the ceilometer component.
#        find and bash is added to tox.ini for removing ugly warnings.
unittest:

    rpm_deps: [
      python-ceilometer,
      mongodb-server,
      python-devel,
      python-tox,
      python-pip,
      python-keystoneclient,
      python-keystonemiddleware,
      python-babel,
      python-coverage,
      python-croniter,
      python-pecan,
      python-httplib2,
      python-mock,
      python-oslo-sphinx,
      python-oslo-db,
      python-oslo-vmware,
      python-oslo-messaging,
      python-oslo-serialization,
      python-oslotest,
      python-jsonpath-rw,
      python-ceilometerclient,
      python-glanceclient,
      python-novaclient,
      python-neutronclient,
      python-swiftclient,
      python-psycopg2,
      python-pymongo,
      pysnmp,
      python-subunit,
      python-sphinx,
      python-tooz,
      python-pep8,
      python-paste,
      python-paste-deploy,
      python-testrepository,
      python-testscenarios,
      python-testtools,
      python-wsme,
      python-werkzeug,
      python-webtest,
      python-thrift-0.9.0,
      python-happybase-0.6
    ]

    remove_rpm: [
      python-ceilometer
    ]

    run:
        tox --sitepackages -v -e py27 2>&1 | tee ../logs/testrun.log;


# Common rpm deps needed for all tester types (pep8 / unittest / functional)
#
# (N.B.) We read the version from setup.cfg and force PBR to use that version
#        explicitly. It would be better to use ConfigParser, but I can't work
#        out how to escape a python script in this file.
#
# (migi) Deps (not directly needed - copr):
#        python-pip is dep for python-pbr and python-hacking
#        python-mccabe is dep for python-hacking and python-flake8
#        pyflakes is dep for python-flake8
#        python-pep8 is dep for python-flake8
#
#        python-virtualenv is also available in copr and it gets
#        installed from copr as dependency for python-tox.
rpm_deps: [
    git,
    python-virtualenv,
    python-pip-1.5.6,
    python-pbr-0.10.8,
    python-tox-1.8.1,
    pyflakes-0.8.1,
    python-mccabe-0.2.1,
    python-pep8-1.5.6,
    python-flake8-2.1.0,
    "{{ hostvars[inventory_hostname][tester.component.tox_target]['rpm_deps'] }}"
]


# The rpms that shouldn't be installed when running tests
# python-ceilometer is installed and then removed to satisfy other dependencies
remove_rpm: [
    "{{ hostvars[inventory_hostname][tester.component.tox_target]['remove_rpm'] }}"
]


# (N.B.) We truncate *requirements.txt to ensure we're only using installed
#        non-test packages.
#
#        We remove ceilometer's install_command from tox.ini because it force
#        upgrades everything, regardless of --sitepackages.
ceilometer_virt_run_config:

  run: >
      set -o pipefail;
      rpm -qa | sort > ../logs/installed-rpms.log;
      truncate --size 0 requirements.txt;
      truncate --size 0 test-requirements.txt;
      sed -i "s/^install_command\s*=.*$//" tox.ini;
      {{ hostvars[inventory_hostname][tester.component.tox_target]['run'] }}


# NOTE: This is the main section. It must exist.
test_config:
  virt:
    RedHat-7:
      setup:
        install: "{{rpm_deps}}"
        remove: "{{remove_rpm}}"
      run: "{{ceilometer_virt_run_config.run}}"
