#!/usr/bin/env python
#
# Wipes any packet installation code from tox.ini in order to be able
# to run tox commands using system packages.
#
import os
import re

f = open('tox.ini', 'r+')
data = f.read()

# remove install_commands
data = re.sub(r'\s*install_command.*', '', data)
# remove pip install commands
data = re.sub(r'(?m)^\s*pip (.*)?install.*\n?', '', data)
# remove deps
data = re.sub(r'(?m)^\s*deps.*\n?(^\s+.*\n?)?', '', data)

f.seek(0)
f.write(data)
f.truncate()
