#!/usr/bin/env python
#
# Wipes any packet installation code from tox.ini in order to be able
# to run tox commands using system packages.
#
import os
import re

f = open('tox.ini', 'r+')
data = f.read()

# consolidate contiuation line breaks
data = re.sub(
            r'^(.*)\\\n\s*([^\r\n]+)\n',
            r'\1\2\n',
            data,
            flags=re.MULTILINE)

# remove install_commands
data = re.sub(r'\s*install_command.*', '', data)
# remove pip install commands
data = re.sub(r'(?m)^\s*pip (.*)?install.*\n?', '', data)

# remove deps, single and multiline ones
data = re.sub(
            r'^\s*deps.*\n(([^\S\n]+[^\n]+\n)+)?',
            r'',
            data,
            flags=re.MULTILINE)

f.seek(0)
f.write(data)
f.truncate()
